version: 2
jobs:
  build:
    working_directory: ~/apt_test
    docker:
      - image: ubuntu:xenial
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
    steps:
      - checkout

      - run: apt-get update && apt-get install -y apt-utils build-essential python3-pip git
      - run: python3 -m pip install pip --upgrade
      - run: python3 -m pip install wheel pipenv

      # Execute tests
      - run: pipenv install && pipenv run python -m pytest -vvv -s tests/test_apt_install.py

      # Upload results
      - store_test_results:
          path: ./test-results
      - store_artifacts:
          path: ./test-results